### ISSUE TITLE
zmq lib is required for lnd communicating with bitcoind

### ISSUE THREAD

**Issue by 0xbytes** [jochemin/raspnode#11]
when running 
./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-/usr/local/BerkeleyDB.4.8/lib" --enable-upnp-default

 the result is

Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = no
  with test     = yes
  with bench    = yes
  with upnp     = auto
  use asm       = yes
  debug enabled = no
  werror        = no

zmq = yes is required for lnd communicating with bitcoind

after
sudo apt-get install libzmq3-dev

Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = yes
  with test     = yes
  with bench    = yes
  with upnp     = auto
  use asm       = yes
  debug enabled = no
  werror        = no

**Comment by jochemin** [comment]
Added to prerequesites.

Thank you!
