### ISSUE TITLE
Running the script without arguments fails

### ISSUE THREAD

**Issue by martinatime** [jochemin/raspnode#12]
I have a brand new install of raspbian stretch that I was attempting to run the script on. I got some error related to uninitialized variable $1 (sorry, I didn't capture the error). I was able to comment out the "if [$1 == secure]" stanza and the script ran correctly on the subsequent run. My shell scripting fu is not very strong so I don't have a good suggestion for a fix. Thanks for the script.

**Comment by simonk83** [comment]
Same issue here:

line 284: $1: unbound variable

**Comment by jochemin** [comment]
My bad. Solved now. Sorry for the inconvenience.
