### ISSUE TITLE
Question: bitcoind sync time

### ISSUE THREAD

**Issue by offerm** [jochemin/raspnode#15]
Hi,

Do you need bitcoind to be fully synced with the network for LND?
If so, how much time does it take for it to download the full chain?

Thanks

**Comment by Amiga500** [comment]
Hi, yes. About from 2 to 4 weeks to download.

**Comment by jochemin** [comment]
As Amiga500 said, yes you need Bitcoin client synced. Sync takes 4 weeks more le less.
