### ISSUE TITLE
bcache & userhd options

### ISSUE THREAD

**Issue by anandanand84** [jochemin/raspnode#2]
What is bcache and userhd options in https://github.com/jochemin/raspnode/blob/master/raspnode.sh#L196

I dont see those in full bitcoin configuration file, is that dbcache?

https://en.bitcoin.it/wiki/Running_Bitcoin#Sample_Bitcoin.conf

**Comment by jochemin** [comment]
Typos.

Is dbcache=100 for database cache and usehd=1 to use hierarchical deterministic key generation (HD) after BIP32
