### ISSUE TITLE
Use specific tag of bitcoind instead of master

### ISSUE THREAD

**Issue by anandanand84** [jochemin/raspnode#3]
I see the installation of bitcoin core is from master branch which is unstable and not secure. It should be from a specific tag like 0.16

https://github.com/jochemin/raspnode/blob/master/raspnode.sh#L178

**Comment by 1blockologist** [comment]
you should send a pull request

**Comment by vnnkl** [comment]
opened one
https://github.com/jochemin/raspnode/pull/4

**Comment by jochemin** [comment]
Merged! Thank you!
