### ISSUE TITLE
Bitcoin Core install fails due to Boost not being installed by default on Raspberry Pis

### ISSUE THREAD

**Issue by merehap** [jochemin/raspnode#6]
The following command (or something similar) could be included in the script to fix this.

sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev

This is with Raspian running on a Raspberry Pi 3, Model B from CanaKit.

**Comment by jochemin** [comment]
Added to prerequisites!
