### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by deuteragenie** [jochemin/raspnode#7]
Maybe you want to configure iptables with rate limiting to prevent DOS ?

**Comment by jochemin** [comment]
I'm concerned about the security of the lightning nodes, probably iptables can be configured to prevent some attacks but I am not familiar with the configuration. I am open to proposals!

**Comment by deuteragenie** [comment]
Here is a starting point:
https://making.pusher.com/per-ip-rate-limiting-with-iptables/

**Comment by jochemin** [comment]
Working on this, tomorrow I'll add securization.

**Comment by jochemin** [comment]
Added rate limiting:

All trafic from LAN allowed
Limited total incoming connections to 250
Limited SSH connections to port 22 to 2
Limited total connections to port 8333 (Bitcoin Mainnet) to 120
Limited total connections to port 9735 (Lightning Network) to 120
Limited to 6 connections from one IP to port 8333
Limited to 6 connections from one IP to port 9735
